import type React from "react";

// 设置面板 Select 触发器的共用定义:全宽版与固定 220px 紧凑版(GeneralPanel)
// 仅宽度不同,组件内在两个完整样式间切换,不做行内合并(AGENTS.md 样式规范)。
const settingsSelectTriggerBase: React.CSSProperties = {
  width: "100%",
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 8,
  padding: "8px 28px 8px 10px",
  background: "var(--bg-input)",
  border: "1px solid var(--border-medium)",
  borderRadius: 8,
  color: "var(--text-primary)",
  fontSize: 13,
  fontFamily: "var(--font-ui)",
  cursor: "pointer",
  textAlign: "left" as const,
  outline: "none",
};

export const dialogs = {
  modalOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "var(--overlay-bg)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modalBox: {
    width: "min(920px, calc(100vw - 48px), calc((100vh - 96px) * 4 / 3))",
    aspectRatio: "4 / 3",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 14,
    boxShadow: "var(--shadow-popover)",
    display: "flex",
    flexDirection: "row" as const,
    overflow: "hidden",
  },
  settingsNav: {
    width: 180,
    flexShrink: 0,
    background: "var(--bg-sidebar)",
    borderRight: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column" as const,
    padding: "16px 10px 12px",
  },
  settingsNavTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.8,
    textTransform: "uppercase" as const,
    padding: "0 8px 10px",
  },
  settingsNavItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "7px 10px",
    border: "none",
    borderRadius: 7,
    background: "none",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-secondary)",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 0.12s, color 0.12s",
  },
  settingsNavExternalIcon: {
    marginLeft: "auto",
    color: "var(--text-hint)",
    flexShrink: 0,
  },
  settingsNavSectionLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.6,
    textTransform: "uppercase" as const,
    padding: "12px 10px 6px",
  },
  settingsNavSectionLabelFirst: {
    padding: "4px 10px 6px",
  },
  settingsContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    minWidth: 0,
  },
  settingsContentHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 20px 14px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  settingsContentTitle: { fontSize: 15, fontWeight: 700, color: "var(--text-primary)" },
  settingsBody: { flex: 1, overflowY: "auto" as const, padding: "18px 20px" },
  // settingsBody 的纵向布局变体(GeneralPanel:字段区块自上而下排列)
  settingsBodyColumn: {
    flex: 1,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: 0,
    padding: "20px",
  },
  shortcutsPanelBody: {
    flex: 1,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column",
    padding: "20px",
  },
  shortcutsPanelGroups: {
    display: "flex",
    flexDirection: "column",
    gap: 22,
  },
  shortcutsPanelError: {
    color: "var(--danger)",
    fontSize: 12.5,
    marginBottom: 14,
  },
  shortcutsPanelLoading: {
    color: "var(--text-hint)",
    fontSize: 13,
  },
  settingsFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    padding: "12px 20px",
    borderTop: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  modalCloseBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    color: "var(--text-hint)",
  },
  modalSection: { marginBottom: 22 },
  modalSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.8,
    textTransform: "uppercase" as const,
    marginBottom: 10,
  },
  modalField: { marginBottom: 14 },
  modalLabel: {
    display: "block",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 5,
  },
  modalLabelHint: { fontSize: 11.5, fontWeight: 400, color: "var(--text-hint)", marginLeft: 6 },
  modalSelect: {
    width: "100%",
    padding: "8px 28px 8px 10px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-ui)",
    outline: "none",
    cursor: "pointer",
  },
  settingsFieldWarning: {
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
    marginTop: 6,
    fontSize: 11,
    color: "var(--warning)",
    lineHeight: 1.5,
  },
  settingsFieldWarningIcon: {
    flexShrink: 0,
    marginTop: 1,
    color: "var(--warning)",
  },
  settingsNumberInput: {
    width: 86,
    height: 28,
    padding: "0 6px",
    borderRadius: 6,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "var(--font-mono)",
    textAlign: "center" as const,
    outline: "none",
  },
  settingsSelectTrigger: settingsSelectTriggerBase,
  // 通用设置面板的固定宽度下拉(语言 / 任务窗口等)
  settingsSelectTriggerCompact: {
    ...settingsSelectTriggerBase,
    width: 220,
  },
  settingsSelectIcon: {
    flexShrink: 0,
    color: "var(--text-hint)",
    transform: "none",
    transition: "transform 0.15s",
  },
  settingsSelectIconOpen: {
    flexShrink: 0,
    color: "var(--text-hint)",
    transform: "rotate(180deg)",
    transition: "transform 0.15s",
  },
  settingsSelectContent: {
    zIndex: 2000,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 4,
    minWidth: "var(--radix-select-trigger-width)",
    overflow: "hidden",
  },
  settingsSelectViewport: {
    padding: 0,
  },
  settingsSelectOption: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13,
    outline: "none",
    position: "relative",
    transition: "background 0.12s ease",
  },
  settingsSelectOptionSelected: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    cursor: "pointer",
    background: "var(--bg-selected)",
    color: "var(--text-primary)",
    fontSize: 13,
    outline: "none",
    position: "relative",
    transition: "background 0.12s ease",
  },
  settingsSelectIndicator: {
    position: "absolute",
    right: 10,
    display: "inline-flex",
    alignItems: "center",
    color: "var(--text-primary)",
  },
  settingsSelectCheck: {
    flexShrink: 0,
  },
  shortcutField: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  shortcutFieldLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 5,
    display: "block",
  },
  shortcutSelectTrigger: {
    width: 132,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "6px 8px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    color: "var(--text-primary)",
    cursor: "pointer",
    outline: "none",
  },
  shortcutSelectTriggerDisabled: {
    cursor: "default",
    opacity: 0.65,
  },
  shortcutReadonlyKey: {
    width: 132,
    display: "inline-flex",
    alignItems: "center",
    padding: "6px 8px",
    background: "transparent",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    color: "var(--text-secondary)",
    cursor: "default",
    userSelect: "none",
  },
  shortcutHint: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    flexWrap: "wrap",
    color: "var(--text-hint)",
    fontSize: 11.5,
    lineHeight: 1.5,
    marginTop: 2,
  },
  shortcutHintKey: {
    fontSize: "inherit",
    lineHeight: "inherit",
    fontWeight: 600,
    color: "var(--text-hint)",
  },
  shortcutHintSep: {
    opacity: 0.55,
  },
  shortcutToggle: {
    width: 132,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "6px 8px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    color: "var(--text-primary)",
    cursor: "pointer",
    outline: "none",
  },
  shortcutToggleDisabled: {
    cursor: "default",
    opacity: 0.65,
  },
  shortcutToggleKeys: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12.5,
  },
  shortcutSwitchTrack: {
    width: 36,
    height: 20,
    borderRadius: 999,
    padding: 2,
    display: "inline-flex",
    alignItems: "center",
    boxSizing: "border-box" as const,
    flexShrink: 0,
    background: "var(--border-medium)",
    transition: "background 0.15s",
  },
  shortcutSwitchTrackOn: {
    width: 36,
    height: 20,
    borderRadius: 999,
    padding: 2,
    display: "inline-flex",
    alignItems: "center",
    boxSizing: "border-box" as const,
    flexShrink: 0,
    background: "var(--primary-action-bg)",
    transition: "background 0.15s",
  },
  shortcutSwitchThumb: {
    width: 16,
    height: 16,
    borderRadius: 999,
    background: "var(--control-knob-bg)",
    boxShadow: "var(--shadow-switch-thumb)",
    transition: "transform 0.15s",
    transform: "translateX(0)",
  },
  shortcutSwitchThumbOn: {
    width: 16,
    height: 16,
    borderRadius: 999,
    background: "var(--control-knob-bg)",
    boxShadow: "var(--shadow-switch-thumb)",
    transition: "transform 0.15s",
    transform: "translateX(16px)",
  },
  agentPathToggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "9px 12px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    cursor: "pointer",
  },
  agentPathToggleRowDisabled: {
    cursor: "default",
    opacity: 0.65,
  },
  agentPathToggleLabel: {
    fontSize: 12.5,
    color: "var(--text-primary)",
    fontWeight: 500,
  },
  modalTextarea: {
    width: "100%",
    padding: "9px 11px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-primary)",
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    lineHeight: 1.55,
    resize: "vertical" as const,
    outline: "none",
    minHeight: 120,
  },
  modalInput: {
    width: "100%",
    padding: "8px 11px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-primary)",
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  modalCancelBtn: {
    padding: "6px 14px",
    background: "none",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  modalSaveBtn: {
    padding: "6px 16px",
    background: "var(--primary-action-bg)",
    border: "none",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--primary-action-fg)",
    cursor: "pointer",
  },
  modalSaveSelectTrigger: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 12px",
    background: "var(--primary-action-bg)",
    border: "none",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--primary-action-fg)",
    cursor: "pointer",
    outline: "none",
  },
  modalSaveMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    width: "100%",
    border: "none",
    background: "transparent",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--text-primary)",
    cursor: "pointer",
    outline: "none",
  },
  settingsFlexRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  settingsInputWithFlex: {
    flex: 1,
  },
  settingsUnitText: {
    color: "var(--text-hint)",
    fontSize: 12,
  },
} satisfies Record<string, React.CSSProperties>;
