import type React from "react";

export const font = {
  fontPanel: {
    flex: 1,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: 18,
    padding: 20,
  },
  fontSection: {
    padding: "16px 18px",
    borderRadius: 8,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-subtle)",
  },
  fontPreviewSection: {
    padding: "14px 18px",
    borderRadius: 8,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-subtle)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  fontPreviewLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  fontPreviewInner: {
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-card)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  fontPreviewText: {
    fontSize: 13,
    color: "var(--text-primary)",
    lineHeight: 1.5,
  },
  fontPreviewCode: {
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  },
  fontPreviewDivider: {
    height: 1,
    background: "var(--border-dim)",
    margin: "2px 0",
  },
  fontSettingLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  fontSettingHint: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    lineHeight: 1.45,
  },
  fontSizeRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  fontSizeLabelCol: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 3,
    minWidth: 0,
  },
  fontSizeControls: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
  },
  fontSizeInput: {
    width: 54,
    height: 28,
    padding: "0 6px",
    borderRadius: 6,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "var(--font-mono)",
    textAlign: "center" as const,
    outline: "none",
  },
  fontSizeUnit: {
    color: "var(--text-hint)",
  },
  fontSelectorInner: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  fontSelectorLabelSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 3,
  },
  fontSelectorLabelRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fontSelectorResetBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    color: "var(--text-hint)",
    fontSize: 11,
    cursor: "pointer",
    padding: "2px 6px",
    borderRadius: 4,
  },
  fontSelectorTrigger: {
    width: "100%",
  },
  fontSelectorTriggerContent: {
    flex: 1,
    textAlign: "left" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fontSaveBtn: {
    padding: "8px 20px",
    borderRadius: 6,
    border: "none",
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    alignSelf: "flex-end" as const,
  },
} satisfies Record<string, React.CSSProperties>;
