import type React from "react";

const kanbanCloseBtn = {
  width: 24,
  height: 24,
  display: "flex",
  alignItems: "center" as const,
  justifyContent: "center" as const,
  border: "1px solid var(--border-dim)",
  background: "transparent",
  borderRadius: 6,
  cursor: "pointer",
  color: "var(--text-muted)",
  transition: "background 0.12s, color 0.12s, border-color 0.12s",
};

const kanbanProjectHeader = {
  display: "flex",
  alignItems: "center" as const,
  gap: 8,
  marginBottom: 6,
  cursor: "pointer",
  border: "none",
  background: "transparent",
  padding: "2px 4px",
  borderRadius: 6,
  width: "fit-content",
  textAlign: "left" as const,
  transition: "background 0.12s",
};

const kanbanColumnDot = {
  width: 6,
  height: 6,
  borderRadius: "50%",
  flexShrink: 0,
};

const kanbanCard = {
  display: "flex",
  alignItems: "center" as const,
  gap: 6,
  padding: "4px 6px",
  background: "transparent",
  border: "1px solid transparent",
  borderRadius: 6,
  cursor: "pointer",
  textAlign: "left" as const,
  width: "100%",
  transition: "background 0.12s, border-color 0.12s",
};

const railIconBtn = {
  width: 32,
  height: 32,
  display: "flex",
  alignItems: "center" as const,
  justifyContent: "center" as const,
  borderRadius: 8,
  cursor: "pointer",
  transition: "background 0.12s, color 0.12s",
};

export const kanban = {
  kanbanOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "var(--bg-app)",
    zIndex: 50,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden" as const,
  },
  kanbanPane: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflowY: "auto" as const,
    background: "var(--bg-panel)",
    padding: "16px 20px 20px",
  },
  kanbanHeader: {
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    gap: 12,
    marginBottom: 2,
  },
  kanbanCloseBtn: {
    ...kanbanCloseBtn,
  },
  kanbanCloseBtnHover: {
    ...kanbanCloseBtn,
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    borderColor: "var(--border-medium)",
  },
  kanbanTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  kanbanSubtitle: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginBottom: 14,
  },
  kanbanEmpty: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    padding: "48px 24px",
    color: "var(--text-muted)",
    fontSize: 13,
    textAlign: "center" as const,
    gap: 10,
  },
  kanbanProjectBlock: {
    display: "flex",
    flexDirection: "column" as const,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottom: "1px solid var(--border-dim)",
  },
  kanbanProjectHeader: {
    ...kanbanProjectHeader,
  },
  kanbanProjectHeaderHover: {
    ...kanbanProjectHeader,
    background: "var(--bg-hover)",
  },
  kanbanProjectName: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  kanbanProjectPath: {
    fontSize: 11,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono, monospace)",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
    maxWidth: 320,
  },
  kanbanProjectCount: {
    fontSize: 10.5,
    color: "var(--text-hint)",
    fontWeight: 500,
    marginLeft: 2,
  },
  kanbanColumns: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 10,
  },
  kanbanColumn: {
    display: "flex",
    flexDirection: "column" as const,
    background: "var(--bg-elevated, var(--bg-panel))",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    padding: "6px 6px 8px",
    minHeight: 52,
  },
  kanbanColumnHeader: {
    display: "flex",
    alignItems: "center" as const,
    gap: 6,
    padding: "0 4px 4px",
    marginBottom: 2,
    borderBottom: "1px dashed var(--border-dim)",
  },
  kanbanColumnDotRunning: {
    ...kanbanColumnDot,
    background: "var(--accent)",
  },
  kanbanColumnDotAttention: {
    ...kanbanColumnDot,
    background: "var(--warning)",
  },
  kanbanColumnDotAwaiting: {
    ...kanbanColumnDot,
    background: "var(--success)",
  },
  kanbanColumnTitle: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-secondary)",
    letterSpacing: 0.2,
  },
  kanbanColumnCount: {
    fontSize: 10.5,
    color: "var(--text-hint)",
    fontWeight: 500,
    marginLeft: "auto",
    fontVariantNumeric: "tabular-nums" as const,
  },
  kanbanColumnEmpty: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    padding: "6px 4px",
    textAlign: "center" as const,
    fontStyle: "italic" as const,
  },
  kanbanCard: {
    ...kanbanCard,
  },
  kanbanCardHover: {
    ...kanbanCard,
    background: "var(--bg-hover)",
    borderColor: "var(--border-medium)",
  },
  // ProjectRail 底部看板入口按钮 —— 与折叠按钮（ChevronsRight）同款无边框样式
  railKanbanBtn: {
    ...railIconBtn,
    background: "none",
    border: "none",
    color: "var(--text-hint)",
  },
  railKanbanBtnHover: {
    ...railIconBtn,
    background: "var(--bg-hover)",
    border: "none",
    color: "var(--text-muted)",
  },
  railExpandBtn: {
    ...railIconBtn,
    background: "none",
    border: "none",
    color: "var(--text-hint)",
  },
  railExpandBtnHover: {
    ...railIconBtn,
    background: "var(--bg-hover)",
    border: "none",
    color: "var(--text-muted)",
  },
  railExpandBtnOpen: {
    ...railIconBtn,
    background: "var(--accent-subtle)",
    border: "none",
    color: "var(--accent)",
  },
  railExpandIcon: {
    transform: "none",
    transition: "transform 0.18s",
  },
  railExpandIconOpen: {
    transform: "rotate(180deg)",
    transition: "transform 0.18s",
  },
  railAddBtn: {
    ...railIconBtn,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    color: "var(--text-muted)",
  },
  railAddBtnHover: {
    ...railIconBtn,
    background: "var(--bg-hover)",
    border: "1px solid var(--border-medium)",
    color: "var(--text-primary)",
  },
  kanbanCardStatus: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center" as const,
  },
  kanbanCardTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  kanbanCardStar: {
    color: "var(--star-fg)",
    flexShrink: 0,
  },
  kanbanColumnMore: {
    padding: "4px 4px 0",
    fontSize: 11,
    color: "var(--accent)",
    cursor: "pointer",
    border: "none",
    background: "transparent",
    textAlign: "left" as const,
    width: "100%",
  },
} satisfies Record<string, React.CSSProperties>;
