import type React from "react";

export const layout = {
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "var(--bg-root)",
    overflow: "hidden",
  },
  rootRelative: {
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
    background: "var(--bg-root)",
    overflow: "hidden",
    position: "relative" as const,
  },
  appProjectLayer: {
    position: "absolute" as const,
    inset: 0,
    overflow: "hidden",
  },
  appWelcomeLayer: {
    position: "absolute" as const,
    inset: 0,
    zIndex: 5,
  },
  /** 一条项目都没有时的外壳：只挂抽屉（它不依赖 project），右侧留空。
      任务面板强依赖真实 Project，此处无法渲染。 */
  appEmptyShell: {
    position: "absolute" as const,
    inset: 0,
    zIndex: 5,
    display: "flex",
    background: "var(--bg-shell)",
  },
  welcomeBody: {
    height: "100%",
    display: "flex",
    overflow: "hidden",
    background: "var(--bg-shell)",
  },
  welcomeMain: { flex: 1, display: "flex", overflow: "hidden" },
  sidebar: {
    width: 220,
    flexShrink: 0,
    background: "linear-gradient(180deg, var(--bg-sidebar), var(--bg-sidebar-elevated))",
    borderRight: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    padding: "18px 14px 14px",
  },
  sidebarBrand: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "2px 6px 18px",
    marginBottom: 14,
    borderBottom: "1px solid var(--border-dim)",
  },
  sidebarBrandIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: "var(--brand-mark-gradient)",
    padding: 4,
  },
  sidebarBrandBadge: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    borderRadius: 9,
    background: "var(--brand-mark-inner-bg)",
    color: "var(--brand-mark-fg)",
    fontSize: 15,
    fontWeight: 800,
    letterSpacing: 0.6,
  },
  sidebarBrandTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text-primary)",
    lineHeight: 1.2,
  },
  sidebarBrandMeta: { marginTop: 3, fontSize: 12, color: "var(--text-muted)" },
  sidebarFooter: {
    marginTop: "auto",
    paddingTop: 10,
    borderTop: "1px solid var(--border-dim)",
    display: "flex",
    justifyContent: "flex-start",
  },
  welcomePane: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "18px 22px 12px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 500,
  },
  actionRow: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  primaryActionBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    height: 38,
    padding: "0 16px",
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    fontSize: 13.5,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "var(--shadow-xs)",
  },
  projectSectionHeader: { padding: "14px 22px 6px", flexShrink: 0 },
  projectSectionTitle: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)" },
  projectSectionCaption: { marginTop: 4, fontSize: 12, color: "var(--text-muted)" },
  projectList: { flex: 1, overflowY: "auto", padding: "4px 22px 18px" },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    padding: 32,
    textAlign: "center",
  },
  projectBody: { flex: 1, display: "flex", overflow: "hidden" },
  // 非激活项目必须 display:none：visibility:hidden 仍留在 layout tree，会让 macOS
  // WKWebView 的 NSTextInputClient 在中文 IME 拖选时扫描隐藏项目的 RenderText。
  projectBodyVisible: {
    flex: 1,
    display: "flex",
    overflow: "hidden",
    position: "absolute" as const,
    inset: 0,
    pointerEvents: "auto" as const,
    zIndex: 1,
  },
  projectBodyHidden: {
    flex: 1,
    display: "none",
    overflow: "hidden",
    position: "absolute" as const,
    inset: 0,
    pointerEvents: "none" as const,
    zIndex: 0,
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  projectMainStage: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    minHeight: 0,
    position: "relative" as const,
  },
  rightPanelWrap: { position: "relative" as const, display: "flex", flexShrink: 0 },
  rightPanelResizeHandle: {
    position: "absolute" as const,
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    cursor: "col-resize",
    zIndex: 10,
  },
  placeholderView: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center" },
  // ── RightToolbar ───────────────────────────────────────────────────────────
  rightToolbar: {
    width: 44,
    flexShrink: 0,
    background: "var(--bg-sidebar)",
    borderLeft: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    paddingTop: 6,
    paddingBottom: 8,
    gap: 2,
    overflow: "hidden",
  },
} satisfies Record<string, React.CSSProperties>;
