import type React from "react";

import { ROW_HEIGHT } from "../components/file-explorer/types";

const searchFieldBase: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 7,
  minHeight: 30,
  padding: "0 5px 0 9px",
  border: "1px solid var(--border-dim)",
  borderRadius: 6,
  background: "var(--bg-card)",
  boxSizing: "border-box" as const,
  flexShrink: 0,
};

const settingToggleTrackBase: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  flexShrink: 0,
  width: 40,
  height: 24,
  borderRadius: 999,
  padding: 3,
  boxSizing: "border-box" as const,
  transition: "background 0.12s",
};

const settingToggleKnobBase: React.CSSProperties = {
  display: "block",
  flexShrink: 0,
  width: 18,
  height: 18,
  borderRadius: 999,
  background: "var(--control-knob-bg)",
  transition: "transform 0.12s ease",
};

// 通用设置字段区块(标签 + 控件 + 提示的纵向布局),Spaced 变体带区块间距。
const settingFieldBase: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: 5,
};

const settingToggleBase: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 14,
  width: "100%",
  padding: "12px 14px",
  borderRadius: 10,
  border: "1px solid var(--border-dim)",
  background: "var(--bg-subtle)",
  cursor: "pointer",
  textAlign: "left" as const,
};

const sendButtonBase: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  gap: 6,
  minWidth: 82,
  minHeight: 36,
  padding: "7px 15px",
  background: "var(--primary-action-bg)",
  color: "var(--primary-action-fg)",
  border: "none",
  borderRadius: 10,
  fontSize: 13,
  fontWeight: 600,
  cursor: "pointer",
  boxShadow: "var(--shadow-control)",
  whiteSpace: "nowrap",
  transition: "opacity 0.15s, background 0.15s",
};

export const panels = {
  newTaskOuter: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 48px",
    position: "relative",
    overflow: "visible",
  },
  newTaskHeader: {
    marginBottom: 20,
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  newTaskClaudeGif: {
    display: "block",
    width: "min(128px, 32vw)",
    height: "auto",
    marginBottom: 10,
    objectFit: "contain",
  },
  newTaskTitle: {
    display: "block",
    fontSize: 22,
    fontWeight: 700,
    color: "var(--text-primary)",
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  composeCardRelative: {
    width: "100%",
    maxWidth: 820,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 24,
    boxShadow: "var(--shadow-compose)",
    overflow: "visible",
    position: "relative" as const,
  },
  hookFallbackBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    width: "100%",
    maxWidth: 700,
    marginBottom: 10,
    padding: "10px 14px",
    background: "var(--warning-surface)",
    border: "1px solid var(--warning-border)",
    borderRadius: 8,
    boxSizing: "border-box" as const,
  },
  hookFallbackIcon: {
    color: "var(--warning)",
    flexShrink: 0,
    marginTop: 1,
  },
  hookFallbackText: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  },
  // 项目栏状态指示：小圆点(默认)与待确认数量角标
  railStatusDot: {
    position: "absolute" as const,
    bottom: -1,
    right: -1,
    width: 9,
    height: 9,
    borderRadius: "50%",
    borderStyle: "solid" as const,
    borderWidth: 2,
    boxSizing: "border-box" as const,
    // 需高于同容器内 position:relative 的头像层，否则会被盖住
    zIndex: 2,
  },
  // 通用设置：字段区块(标签 + 控件 + 提示)
  settingFieldSpaced: {
    ...settingFieldBase,
    marginTop: 18,
  },
  settingFieldLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 5,
    display: "block",
  },
  settingFieldHint: {
    fontSize: 11,
    color: "var(--text-hint)",
    marginTop: 3,
  },
  // 通用设置：开关(toggle switch)
  settingToggle: settingToggleBase,
  // 平台不适用(如 macOS 上的 Windows 专属项)或加载中:置灰且不可点
  // 新建任务弹窗：字段间距 / 开关的说明行
  newTaskDialogField: { marginTop: 12 },
  newTaskDialogToggleText: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 3,
  },
  newTaskDialogHint: {
    fontSize: 11.5,
    fontWeight: 400,
    color: "var(--text-hint)",
  },
  settingToggleLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  settingToggleTrack: {
    ...settingToggleTrackBase,
    background: "var(--border-medium)",
  },
  settingToggleTrackOn: {
    ...settingToggleTrackBase,
    background: "var(--primary-action-bg)",
  },
  settingToggleKnob: settingToggleKnobBase,
  settingToggleKnobOn: {
    ...settingToggleKnobBase,
    transform: "translateX(16px)",
  },
  composeTextarea: {
    display: "block",
    width: "100%",
    padding: "22px 24px 12px",
    border: "none",
    outline: "none",
    resize: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 14,
    lineHeight: 1.65,
    fontFamily: "var(--font-ui)",
  },
  toolbar: {
    borderTop: "none",
    minHeight: 58,
    padding: "8px 18px 16px",
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "transparent",
    borderRadius: "0 0 24px 24px",
    boxSizing: "border-box" as const,
  },
  toolbarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    flexWrap: "nowrap" as const,
  },
  launchModeBar: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    width: "100%",
    maxWidth: 820,
    marginTop: 8,
    padding: "0 18px",
    boxSizing: "border-box" as const,
  },
  toolbarSpacer: {
    flex: 1,
    minWidth: 8,
  },
  toolbarPlusBtn: {
    width: 26,
    height: 26,
    padding: 0,
    border: "none",
    borderRadius: 6,
    background: "transparent",
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  toolbarIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "5px 7px",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
  },
  toolbarBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    minHeight: 32,
    padding: "5px 8px",
    background: "transparent",
    border: "1px solid transparent",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-muted)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    transition: "background 0.15s, border-color 0.15s, opacity 0.15s",
  },
  toolbarMenuContent: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 4,
    minWidth: 180,
    zIndex: 9999,
  },
  toolbarActionMenuContent: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 6,
    minWidth: 180,
    zIndex: 9999,
  },
  toolbarMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--text-primary)",
    cursor: "pointer",
    outline: "none",
    userSelect: "none" as const,
  },
  toolbarHiddenInput: {
    display: "none",
  },
  toolbarMenuButton: {
    width: "100%",
    gap: 8,
  },
  toolbarMenuItemIcon: {
    width: 14,
    height: 14,
    flexShrink: 0,
  },
  toolbarMenuItemIconMuted: {
    width: 14,
    height: 14,
    flexShrink: 0,
    opacity: 0.72,
  },
  toolbarChevron: {
    opacity: 0.58,
  },
  sendBtn: sendButtonBase,
  sendShortcutIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    minWidth: 18,
    color: "currentColor",
    opacity: 0.95,
  },
  sendShortcutTextKey: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 16,
    height: 14,
    fontSize: 10,
    fontWeight: 700,
    lineHeight: 1,
    fontFamily: "var(--font-ui)",
  },
  kbd: {
    display: "none",
    fontSize: 11,
    opacity: 0,
    background: "transparent",
    borderRadius: 3,
    padding: 0,
    fontFamily: "var(--font-ui)",
  },
  mentionDropdown: {
    position: "absolute" as const,
    bottom: "calc(100% + 6px)",
    left: 0,
    right: 0,
    zIndex: 200,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    boxShadow: "var(--shadow-lg, var(--shadow-md))",
    padding: 4,
    maxHeight: 260,
    overflowY: "auto" as const,
  },
  mentionOption: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 6,
    cursor: "pointer",
    minWidth: 0,
  },
  mentionOptionName: { fontSize: 13, fontWeight: 500, color: "var(--text-primary)", flexShrink: 0 },
  mentionOptionDir: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  mentionSeparator: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px 3px",
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-hint)",
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
    userSelect: "none" as const,
  },
  mentionProjectItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 6,
    cursor: "pointer",
    minWidth: 0,
  },
  mentionCrossHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px 5px",
    fontSize: 11.5,
    fontWeight: 500,
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border-dim)",
    marginBottom: 3,
    userSelect: "none" as const,
  },
  fileExplorerRoot: {
    flexShrink: 0,
    background: "var(--bg-sidebar)",
    borderLeft: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  fileExplorerTopBar: {
    flexShrink: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 5,
    paddingBottom: 8,
    borderBottom: "1px solid var(--border-dim)",
  },
  fileExplorerHeader: {
    height: 40,
    display: "flex",
    alignItems: "center",
    padding: "0 12px",
    flexShrink: 0,
  },
  fileExplorerHeaderTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    textTransform: "uppercase" as const,
    flex: 1,
  },
  fileExplorerIconButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text-hint)",
    padding: 4,
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  fileExplorerRootLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 8px 3px 20px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  fileExplorerRootIcon: {
    width: 5,
    height: 14,
    borderRadius: 2,
    background: "var(--icon-folder-root)",
    flexShrink: 0,
    display: "inline-block",
  },
  fileSearchBar: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 5,
    padding: "0 12px",
  },
  fileSearchBox: {
    ...searchFieldBase,
  },
  // 与上面的文件名输入框同一套度量：同高、同圆角、同边框色、同字号，
  // 只靠右端箭头和 hover 底色区分「这是下拉」。
  fileSearchTypeBox: {
    ...searchFieldBase,
    width: "100%",
    justifyContent: "space-between",
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    fontSize: 12.5,
    textAlign: "left" as const,
    cursor: "pointer",
    outline: "none",
  },
  fileSearchTypeValue: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  fileSearchTypeChevron: {
    flexShrink: 0,
    color: "var(--text-hint)",
    transition: "transform 0.15s",
  },
  fileSearchTypeContent: {
    zIndex: 2000,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 4,
    minWidth: "var(--radix-popover-trigger-width)",
    overflow: "hidden",
  },
  // 行高 26 = 输入框里文字行高（fileSearchInput.height），字号 12.5 也与触发器一致，
  // 列表看起来就是触发器里那行字的自然延伸。
  fileSearchTypeItem: {
    height: 26,
    padding: "0 8px",
    fontSize: 12.5,
  },
  fileSearchIcon: {
    flexShrink: 0,
    color: "var(--text-hint)",
  },
  fileSearchInput: {
    flex: 1,
    minWidth: 0,
    height: 26,
    padding: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    fontSize: 12.5,
  },
  fileSearchClearBtn: {
    width: 20,
    height: 20,
    padding: 0,
    border: "none",
    borderRadius: 4,
    background: "transparent",
    color: "var(--text-hint)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  fileSearchTypeList: {
    maxHeight: 300,
    overflowY: "auto" as const,
  },
  fileSearchTypeSeparator: {
    height: 1,
    background: "var(--border-dim)",
    margin: "4px 2px",
  },
  fileSearchResults: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto" as const,
    padding: "7px 8px 8px",
  },
  fileSearchEmpty: {
    padding: "16px 8px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center" as const,
  },
  fileSearchResult: {
    width: "100%",
    minHeight: 34,
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "5px 7px",
    margin: "1px 0",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-primary)",
    textAlign: "left" as const,
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
    boxSizing: "border-box" as const,
  },
  fileSearchResultActive: {
    background: "var(--bg-selected)",
  },
  fileSearchResultMain: {
    display: "flex",
    flexDirection: "column" as const,
    minWidth: 0,
    flex: 1,
    gap: 1,
  },
  fileSearchResultName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
  },
  fileSearchResultDir: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 11,
    color: "var(--text-hint)",
  },
  fileExplorerTreeScroll: {
    flex: 1,
    overflowY: "auto" as const,
    position: "relative" as const,
  },
  fileExplorerEmpty: {
    padding: "16px 12px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center" as const,
  },
  fileExplorerVirtualRow: {
    position: "absolute" as const,
    width: "100%",
  },
  fileTreeRow: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    height: ROW_HEIGHT,
    paddingRight: 8,
    cursor: "pointer",
    borderRadius: 4,
    margin: "0 4px",
    boxSizing: "border-box" as const,
    userSelect: "none" as const,
  },
  fileTreeRowDragging: {
    background: "var(--bg-selected)",
    opacity: 0.58,
    cursor: "grabbing",
  },
  fileTreeDragPreview: {
    position: "fixed" as const,
    zIndex: 2200,
    display: "flex",
    alignItems: "center",
    gap: 7,
    maxWidth: 320,
    height: 30,
    padding: "0 10px",
    color: "var(--text-primary)",
    background: "var(--bg-card)",
    border: "1px solid var(--accent)",
    borderRadius: 6,
    boxShadow: "var(--shadow-popover)",
    pointerEvents: "none" as const,
    transform: "translate(12px, 10px)",
    fontFamily: "var(--font-ui)",
    fontSize: 12,
    fontWeight: 600,
    boxSizing: "border-box" as const,
  },
  fileTreeDragPreviewLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  fileTreeChevron: {
    width: 12,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    color: "var(--text-hint)",
  },
  fileTreeChevronSpacer: {
    width: 12,
    flexShrink: 0,
  },
  fileTreeRowLabel: {
    fontSize: 12.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    flex: 1,
    fontFamily: "var(--font-ui)",
  },
  fileTreeCreateRow: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    height: ROW_HEIGHT,
    paddingRight: 8,
    margin: "0 4px",
    boxSizing: "border-box" as const,
    background: "var(--bg-selected)",
    borderRadius: 4,
  },
  fileTreeCreateInput: {
    flex: 1,
    minWidth: 0,
    height: 18,
    padding: "0 4px",
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
    color: "var(--text-primary)",
    background: "var(--bg-input, var(--bg-sidebar))",
    border: "1px solid var(--accent)",
    borderRadius: 3,
    outline: "none",
  },
  fileCtxBackdrop: {
    position: "fixed" as const,
    inset: 0,
    zIndex: 999,
  },
  fileCtxMenu: {
    position: "fixed" as const,
    zIndex: 1000,
    background: "var(--bg-sidebar)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    boxShadow: "var(--shadow-popover)",
    minWidth: 148,
    padding: "3px 0",
    fontSize: 12.5,
  },
  fileCtxSeparator: {
    height: 1,
    background: "var(--border-dim)",
    margin: "4px 6px",
  },
  fileCtxMenuItem: {
    display: "block",
    width: "calc(100% - 8px)",
    height: 26,
    padding: "0 10px",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    borderRadius: 3,
    margin: "2px 4px",
    transition: "background 0.1s",
    background: "transparent",
    border: "none",
    textAlign: "left" as const,
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
    lineHeight: "26px",
  },
  attachmentsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    padding: "6px 12px 0",
  },
  imageAttachmentItem: {
    position: "relative",
    flexShrink: 0,
  },
  imageAttachmentImg: {
    width: 64,
    height: 64,
    objectFit: "cover",
    borderRadius: 6,
    display: "block",
    border: "1px solid var(--border)",
  },
  imageAttachmentRemove: {
    position: "absolute",
    top: -5,
    right: -5,
    width: 16,
    height: 16,
    borderRadius: "50%",
    background: "var(--text-muted)",
    border: "none",
    color: "var(--bg)",
    fontSize: 10,
    lineHeight: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },
  textAttachmentChip: {
    position: "relative",
    width: 64,
    height: 64,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-secondary)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    flexShrink: 0,
  },
  textAttachmentIcon: {
    color: "var(--text-muted)",
  },
  textAttachmentSize: {
    fontSize: 10,
    color: "var(--text-hint)",
    fontWeight: 500,
  },
  textAttachmentRemove: {
    position: "absolute",
    top: -5,
    right: -5,
    width: 16,
    height: 16,
    borderRadius: "50%",
    background: "var(--text-muted)",
    border: "none",
    color: "var(--bg)",
    fontSize: 10,
    lineHeight: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },

  // ── HooksPanel (app settings → Hook 集成) ──────────────────────────────────
  hooksPanelBody: {
    flex: 1,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
    padding: "20px",
  },
  hooksPanelLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 5,
    display: "block",
  },
  hooksPanelHint: { fontSize: 11, color: "var(--text-hint)", marginTop: 3, lineHeight: 1.5 },
  hooksPanelCard: {
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    padding: "10px 14px",
    background: "var(--bg-card)",
  },
  hooksPanelRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "6px 0",
    fontSize: 12,
    color: "var(--text-primary)",
    lineHeight: 1.5,
  },
  hooksPanelSubRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "0 0 6px",
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  },
  hooksPanelRowSpacer: { width: 14, flexShrink: 0, display: "inline-block" },
  hooksPanelVersionLow: { color: "var(--warning)" },
  hooksPanelErrorRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "6px 0",
    fontSize: 12,
    color: "var(--danger)",
    lineHeight: 1.5,
  },
  hooksPanelActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap" as const,
    paddingTop: 4,
    borderTop: "1px solid var(--border-dim)",
    marginTop: 2,
  },
  hooksPanelPrimaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 11px",
    background: "var(--primary-action-bg)",
    border: "1px solid transparent",
    borderRadius: 7,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--primary-action-fg)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  hooksPanelSecondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 11px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-primary)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  hooksPanelDangerBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 11px",
    background: "var(--danger-surface)",
    border: "1px solid var(--danger-border)",
    borderRadius: 7,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--danger)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  hooksPanelBtnDisabled: { opacity: 0.5, cursor: "not-allowed" as const },
} satisfies Record<string, React.CSSProperties>;
