import type React from "react";

export const panels = {
  newTaskOuter: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 48px",
    position: "relative",
    overflow: "visible",
  },
  newTaskHeader: {
    marginBottom: 20,
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  newTaskClaudeGif: {
    display: "block",
    width: "min(128px, 32vw)",
    height: "auto",
    marginBottom: 10,
    objectFit: "contain",
  },
  newTaskTitle: {
    display: "block",
    fontSize: 22,
    fontWeight: 700,
    color: "var(--text-primary)",
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  newTaskMeta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-muted)",
  },
  metaChip: {
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
    borderRadius: 4,
    padding: "2px 7px",
    fontSize: 12,
  },
  composeCard: {
    width: "100%",
    maxWidth: 820,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 24,
    boxShadow: "var(--shadow-compose)",
    overflow: "visible",
  },
  agentMissingMdBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    width: "100%",
    maxWidth: 700,
    marginBottom: 10,
    padding: "10px 14px",
    background: "var(--warning-surface)",
    border: "1px solid var(--warning-border)",
    borderRadius: 8,
    boxSizing: "border-box" as const,
  },
  agentMissingMdBody: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  agentMissingMdInitBtn: {
    alignSelf: "flex-start",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    background: "transparent",
    color: "var(--warning)",
    border: "1px solid var(--warning-border)",
    borderRadius: 6,
    fontSize: 12.5,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 120ms ease",
  },
  composeTextarea: {
    display: "block",
    width: "100%",
    padding: "22px 24px 12px",
    border: "none",
    outline: "none",
    resize: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 14,
    lineHeight: 1.65,
    fontFamily: "var(--font-ui)",
  },
  toolbar: {
    borderTop: "none",
    minHeight: 58,
    padding: "8px 18px 16px",
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "transparent",
    borderRadius: "0 0 24px 24px",
    boxSizing: "border-box" as const,
  },
  toolbarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    flexWrap: "nowrap" as const,
  },
  launchModeBar: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    width: "100%",
    maxWidth: 820,
    marginTop: 8,
    padding: "0 18px",
    boxSizing: "border-box" as const,
  },
  toolbarSpacer: {
    flex: 1,
    minWidth: 8,
  },
  toolbarPlusBtn: {
    width: 26,
    height: 26,
    padding: 0,
    border: "none",
    borderRadius: 6,
    background: "transparent",
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  toolbarIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "5px 7px",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
  },
  toolbarDivider: {
    width: 1,
    height: 18,
    background: "var(--border-dim)",
    margin: "0 2px",
    flexShrink: 0,
  },
  toolbarBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    minHeight: 32,
    padding: "5px 8px",
    background: "transparent",
    border: "1px solid transparent",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-muted)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    transition: "background 0.15s, border-color 0.15s, opacity 0.15s",
  },
  toolbarBtnActive: {
    background: "transparent",
    border: "1px solid transparent",
    color: "var(--accent)",
  },
  toolbarMenuContent: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 4,
    minWidth: 180,
    zIndex: 9999,
  },
  toolbarActionMenuContent: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 6,
    minWidth: 230,
    zIndex: 9999,
  },
  toolbarMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--text-primary)",
    cursor: "pointer",
    outline: "none",
    userSelect: "none" as const,
  },
  toolbarMenuSeparator: {
    height: 1,
    background: "var(--border-dim)",
    margin: "6px 6px",
  },
  toolbarMenuItemIcon: {
    width: 14,
    height: 14,
    flexShrink: 0,
  },
  toolbarSwitchTrack: {
    width: 36,
    height: 20,
    borderRadius: 999,
    padding: 2,
    background: "var(--border-medium)",
    display: "inline-flex",
    alignItems: "center",
    boxSizing: "border-box" as const,
    transition: "background 0.15s",
  },
  toolbarSwitchThumb: {
    width: 16,
    height: 16,
    borderRadius: 999,
    background: "var(--bg-card)",
    boxShadow: "var(--shadow-switch-thumb)",
    transition: "transform 0.15s",
  },
  sendSplit: {
    display: "inline-flex",
    minHeight: 32,
    flexShrink: 0,
  },
  saveTodoBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "6px 12px",
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    transition: "opacity 0.15s",
  },
  sendBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minWidth: 82,
    minHeight: 36,
    padding: "7px 15px",
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    border: "none",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "var(--shadow-control)",
    whiteSpace: "nowrap" as const,
    transition: "opacity 0.15s, background 0.15s",
  },
  sendShortcutIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    minWidth: 18,
    color: "currentColor",
    opacity: 0.95,
  },
  sendShortcutTextKey: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 16,
    height: 14,
    fontSize: 10,
    fontWeight: 700,
    lineHeight: 1,
    fontFamily: "var(--font-ui)",
  },
  kbd: {
    display: "none",
    fontSize: 11,
    opacity: 0,
    background: "transparent",
    borderRadius: 3,
    padding: 0,
    fontFamily: "var(--font-ui)",
  },
  dropdownPanel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    zIndex: 100,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 4,
    minWidth: 220,
  },
  dropdownOption: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    cursor: "pointer",
  },
  fileChipsRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 6,
    padding: "10px 14px 4px",
    borderBottom: "1px solid var(--border-dim)",
  },
  fileChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 8px 3px 7px",
    background: "var(--accent-subtle)",
    border: "1px solid color-mix(in srgb, var(--accent) 30%, transparent)",
    borderRadius: 6,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--accent)",
    maxWidth: 240,
  },
  fileChipName: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const },
  fileChipRemove: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    display: "flex",
    alignItems: "center",
    color: "var(--accent)",
    opacity: 0.6,
    marginLeft: 1,
    flexShrink: 0,
  },
  mentionDropdown: {
    position: "absolute" as const,
    bottom: "calc(100% + 6px)",
    left: 0,
    right: 0,
    zIndex: 200,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    boxShadow: "var(--shadow-lg, var(--shadow-md))",
    padding: 4,
    maxHeight: 260,
    overflowY: "auto" as const,
  },
  mentionOption: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 6,
    cursor: "pointer",
    minWidth: 0,
  },
  mentionOptionName: { fontSize: 13, fontWeight: 500, color: "var(--text-primary)", flexShrink: 0 },
  mentionOptionDir: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  mentionSeparator: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px 3px",
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-hint)",
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
    userSelect: "none" as const,
  },
  mentionProjectItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 6,
    cursor: "pointer",
    minWidth: 0,
  },
  mentionCrossHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px 5px",
    fontSize: 11.5,
    fontWeight: 500,
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border-dim)",
    marginBottom: 3,
    userSelect: "none" as const,
  },
} satisfies Record<string, React.CSSProperties>;
