import type React from "react";

const skillRowManageBase: React.CSSProperties = {
  padding: "6px 12px",
  background: "transparent",
  border: "1px solid var(--border-medium)",
  borderRadius: 7,
  fontSize: 12.5,
  fontWeight: 500,
  color: "var(--text-secondary)",
  cursor: "pointer",
  whiteSpace: "nowrap",
};

const dialogPrimaryBase: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  gap: 6,
  padding: "6px 12px",
  background: "var(--primary-action-bg)",
  border: "none",
  borderRadius: 7,
  fontSize: 12.5,
  fontWeight: 600,
  color: "var(--primary-action-fg)",
  cursor: "pointer",
};

const agentBtnBase: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  gap: 8,
  padding: "8px 14px",
  background: "var(--bg-card)",
  border: "1px solid var(--border-medium)",
  borderRadius: 8,
  fontSize: 13,
  fontWeight: 500,
  color: "var(--text-secondary)",
  cursor: "pointer",
  flex: 1,
  justifyContent: "center",
};

export const skillHub = {
  // ── Settings panel ─────────────────────────────────────────────────────────
  skillsPanelBody: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "20px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 16,
  },
  skillsPanelField: { display: "flex", flexDirection: "column" as const, gap: 6 },
  skillsPanelLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    display: "block",
  },
  skillsPanelPathRow: { display: "flex", alignItems: "stretch", gap: 8 },
  skillsPanelPathBox: {
    flex: 1,
    minWidth: 0,
    padding: "8px 12px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    color: "var(--text-primary)",
  },
  skillsPanelPathText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  skillsPanelPathEmpty: { color: "var(--text-hint)" },
  skillsPanelPickBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 14px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  skillsPanelClearBtn: {
    display: "inline-flex",
    alignItems: "center",
    padding: "8px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  skillsPanelHint: { fontSize: 11, color: "var(--text-hint)" },
  skillsPanelMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
  },
  skillsPanelMetaLabel: { fontSize: 11, fontWeight: 600, color: "var(--text-hint)" },
  skillsPanelMetaValue: { fontSize: 12.5, fontWeight: 600, color: "var(--text-primary)" },
  skillsPanelError: {
    padding: "8px 12px",
    background: "var(--danger-subtle)",
    border: "1px solid var(--danger)",
    borderRadius: 8,
    fontSize: 12,
    color: "var(--danger)",
  },

  // ── SkillHubView (welcome page main area) ─────────────────────────────────
  skillHubBody: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    padding: "24px 28px",
    overflow: "hidden",
  },
  skillHubEmpty: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    color: "var(--text-muted)",
  },
  skillHubEmptyTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-secondary)" },
  skillHubEmptyHint: { fontSize: 12.5, color: "var(--text-muted)", maxWidth: 380, textAlign: "center" as const },
  skillHubEmptyBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 14px",
    background: "var(--primary-action-bg)",
    border: "none",
    borderRadius: 8,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--primary-action-fg)",
    cursor: "pointer",
    marginTop: 6,
  },
  skillHubHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    marginBottom: 14,
  },
  skillHubHeaderMain: { flex: 1, minWidth: 0 },
  skillHubHeaderTitle: { fontSize: 18, fontWeight: 700, color: "var(--text-primary)", marginBottom: 4 },
  skillHubHeaderPath: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  skillHubHeaderBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 14px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  skillHubMeta: { fontSize: 12, color: "var(--text-hint)", marginBottom: 12 },
  skillHubError: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "9px 12px",
    background: "var(--danger-subtle)",
    border: "1px solid var(--danger)",
    borderRadius: 8,
    fontSize: 12.5,
    color: "var(--danger)",
    marginBottom: 12,
  },
  skillHubList: {
    flex: 1,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  skillHubEmptyList: {
    padding: "32px 16px",
    fontSize: 12.5,
    color: "var(--text-hint)",
    textAlign: "center" as const,
  },

  // ── Skill row ─────────────────────────────────────────────────────────────
  skillRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    transition: "border-color 0.12s",
  },
  skillRowMain: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" as const, gap: 3 },
  skillRowTitle: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  skillRowDirName: {
    fontSize: 11,
    fontWeight: 500,
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
  },
  skillRowDesc: {
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap" as const,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
  },
  skillRowDescEmpty: { fontSize: 12, color: "var(--text-hint)", fontStyle: "italic" as const },
  skillRowMeta: {
    fontSize: 11.5,
    color: "var(--text-hint)",
  },
  skillRowError: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "var(--danger)",
  },
  skillRowActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  skillRowManageBtn: skillRowManageBase,
  skillRowDeleteBtn: {
    width: 30,
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "transparent",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    color: "var(--danger)",
    cursor: "pointer",
  },

  // ── Manage dialog ─────────────────────────────────────────────────────────
  skillDialogBox: {
    width: "min(640px, calc(100vw - 48px))",
    maxHeight: "min(80vh, 720px)",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 14,
    boxShadow: "var(--shadow-popover)",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  skillDialogHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "16px 20px 14px",
    borderBottom: "1px solid var(--border-dim)",
  },
  skillDialogHeaderMain: { flex: 1, minWidth: 0 },
  skillDialogTitle: { fontSize: 16, fontWeight: 700, color: "var(--text-primary)" },
  skillDialogSubtitle: {
    fontSize: 11.5,
    fontWeight: 500,
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    marginTop: 2,
  },
  skillDialogDesc: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap" as const,
    marginTop: 8,
  },
  skillDialogToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 20px 10px",
  },
  skillDialogSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.6,
    textTransform: "uppercase" as const,
  },
  skillDialogPrimaryBtn: dialogPrimaryBase,
  skillDialogTabs: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "0 20px 12px",
  },
  skillDialogTab: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minHeight: 30,
    padding: "5px 10px",
    background: "transparent",
    border: "1px solid var(--border-dim)",
    borderRadius: 7,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  skillDialogTabActive: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minHeight: 30,
    padding: "5px 10px",
    background: "var(--control-active-bg)",
    border: "1px solid var(--accent)",
    borderRadius: 7,
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--control-active-fg)",
    cursor: "pointer",
  },
  skillDialogTabCount: {
    minWidth: 18,
    padding: "1px 5px",
    borderRadius: 999,
    background: "var(--bg-hover)",
    color: "var(--text-hint)",
    fontSize: 11,
    fontWeight: 700,
    textAlign: "center" as const,
  },
  skillDialogList: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "0 20px 20px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  skillDialogEmpty: {
    padding: "24px 16px",
    fontSize: 12.5,
    color: "var(--text-hint)",
    textAlign: "center" as const,
  },

  // ── Installed-project row ─────────────────────────────────────────────────
  skillInstallRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
  },
  skillInstallRowMain: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" as const, gap: 4 },
  skillInstallRowTitle: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" },
  skillInstallRowMeta: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11.5,
    color: "var(--text-hint)",
    overflow: "hidden",
  },
  skillInstallRowSep: { color: "var(--text-hint)" },
  skillInstallRowPath: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontFamily: "var(--font-mono)",
  },
  skillInstallAgentLogo: { width: 12, height: 12 },
  skillInstallRowWarn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "var(--warning)",
  },
  skillInstallUninstallBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 10px",
    background: "var(--danger-surface)",
    border: "1px solid var(--danger-border)",
    borderRadius: 7,
    fontSize: 12,
    color: "var(--danger)",
    cursor: "pointer",
  },

  // ── Install dialog ────────────────────────────────────────────────────────
  // Install dialog 嵌套在 SkillManageDialog 内部时，避免叠加双层 backdrop。
  // 自身仍占据全屏以接收 overlay click 关闭，但背景透明。
  skillInstallOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "transparent",
    zIndex: 1100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  skillInstallDialogBox: {
    width: "min(480px, calc(100vw - 48px))",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 14,
    boxShadow: "var(--shadow-popover)",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  // 通用 dropdown trigger 样式（与 settings panel 视觉一致，但避免跨模块借用 token）
  skillInstallSelectTrigger: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "8px 28px 8px 10px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
    textAlign: "left" as const,
    outline: "none",
  },
  skillInstallSelectCheck: { flexShrink: 0 },
  skillInstallProjectSearchIcon: { flexShrink: 0 },
  skillInstallDialogHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 20px",
    borderBottom: "1px solid var(--border-dim)",
  },
  skillInstallDialogTitle: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)" },
  skillInstallDialogBody: {
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  skillInstallField: { display: "flex", flexDirection: "column" as const, gap: 6 },
  skillInstallLabel: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  skillInstallProjectPopoverContent: {
    zIndex: 2000,
    width: "var(--radix-popover-trigger-width)",
    minWidth: 220,
    maxWidth: 360,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    overflow: "hidden",
  },
  skillInstallProjectSearch: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "8px 10px",
    borderBottom: "1px solid var(--border-dim)",
  },
  skillInstallProjectSearchInput: {
    flex: 1,
    minWidth: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
  },
  skillInstallProjectSearchClear: {
    display: "flex",
    alignItems: "center",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 2,
    color: "var(--text-hint)",
    borderRadius: 4,
  },
  skillInstallProjectList: {
    maxHeight: 240,
    overflowY: "auto" as const,
    padding: 4,
  },
  skillInstallProjectOption: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
    padding: "6px 10px",
    background: "none",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-ui)",
    outline: "none",
    textAlign: "left" as const,
  },
  skillInstallProjectOptionSelected: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
    padding: "6px 10px",
    background: "var(--bg-hover)",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-ui)",
    outline: "none",
    textAlign: "left" as const,
  },
  skillInstallProjectOptionText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  skillInstallProjectLimitHint: {
    padding: "7px 10px 8px",
    fontSize: 11.5,
    color: "var(--text-hint)",
    borderTop: "1px solid var(--border-dim)",
  },
  skillInstallAgentRow: { display: "flex", gap: 8 },
  skillAgentBtn: agentBtnBase,
  skillAgentBtnActive: {
    ...agentBtnBase,
    background: "var(--bg-selected)",
    borderColor: "var(--accent)",
    color: "var(--text-primary)",
  },
  skillInstallNotice: {
    padding: "8px 12px",
    background: "var(--warning-subtle, var(--bg-hover))",
    border: "1px solid var(--warning, var(--border-medium))",
    borderRadius: 8,
    fontSize: 12,
    color: "var(--warning, var(--text-secondary))",
  },
  skillInstallEmptyOption: {
    padding: "8px 12px",
    fontSize: 12.5,
    color: "var(--text-hint)",
  },
  skillInstallDialogFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    padding: "12px 20px",
    borderTop: "1px solid var(--border-dim)",
  },

  // ── Conflict dialog ───────────────────────────────────────────────────────
  skillConflictOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "var(--overlay-bg)",
    zIndex: 1200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  skillConflictBox: {
    width: "min(440px, calc(100vw - 48px))",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 14,
    boxShadow: "var(--shadow-popover)",
    overflow: "hidden",
  },
  skillConflictHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "14px 20px 12px",
    borderBottom: "1px solid var(--border-dim)",
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  skillConflictBody: {
    padding: "14px 20px",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  skillConflictPath: {
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--text-primary)",
    padding: "6px 10px",
    background: "var(--bg-input)",
    borderRadius: 6,
    wordBreak: "break-all" as const,
  },
  skillConflictTarget: { fontSize: 11.5, color: "var(--text-hint)" },
  skillConflictFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    padding: "12px 20px",
    borderTop: "1px solid var(--border-dim)",
  },
  skillConflictSkipBtn: {
    padding: "6px 14px",
    background: "var(--bg-hover)",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-primary)",
    cursor: "pointer",
  },
  skillConflictOverwriteBtn: {
    padding: "6px 14px",
    background: "var(--danger)",
    border: "none",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--primary-action-fg)",
    cursor: "pointer",
  },
} satisfies Record<string, React.CSSProperties>;
