import type React from "react";

const repoSelectorBarBase = {
  display: "flex",
  alignItems: "center",
  gap: 6,
  width: "calc(100% - 20px)",
  margin: "6px 10px 4px",
  padding: "5px 9px",
  background: "var(--bg-card)",
  border: "1px solid var(--border-dim)",
  borderRadius: 6,
  cursor: "pointer",
  userSelect: "none" as const,
  transition: "background 0.1s, opacity 0.1s",
  textAlign: "left" as const,
} satisfies React.CSSProperties;

const branchBarBase = {
  display: "flex",
  alignItems: "center",
  gap: 6,
  margin: "0 10px 4px",
  padding: "5px 9px",
  background: "var(--bg-card)",
  border: "1px solid var(--border-dim)",
  borderRadius: 6,
  cursor: "pointer",
  userSelect: "none" as const,
  transition: "background 0.1s",
  textAlign: "left" as const,
} satisfies React.CSSProperties;

const taskPanelBase = {
  width: 260,
  flexShrink: 0,
  background: "var(--bg-sidebar)",
  borderRight: "1px solid var(--border-dim)",
  display: "flex",
  flexDirection: "column" as const,
  overflow: "hidden",
} satisfies React.CSSProperties;

const taskPanelCollapsedNewBtnBase = {
  width: 32,
  height: 32,
  border: "1px solid var(--border-dim)",
  borderRadius: 8,
  background: "var(--bg-card)",
  cursor: "pointer",
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
} satisfies React.CSSProperties;

const newTaskRowBase = {
  display: "flex",
  alignItems: "center",
  gap: 8,
  width: "calc(100% - 20px)",
  margin: "6px 10px 2px",
  padding: "6px 10px",
  border: "none",
  cursor: "pointer",
  textAlign: "left" as const,
  borderRadius: 6,
  transition: "background 0.1s",
} satisfies React.CSSProperties;

export const task = {
  taskPanel: taskPanelBase,
  taskPanelCollapsedRoot: {
    ...taskPanelBase,
    width: 52,
    alignItems: "center",
    gap: 12,
    padding: "10px 0",
    boxSizing: "border-box" as const,
  },
  taskPanelCollapsed: {
    width: 52,
    alignItems: "center",
    gap: 12,
    padding: "10px 0",
    boxSizing: "border-box" as const,
  },
  taskPanelCollapsedBody: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 10,
    flex: 1,
    width: "100%",
  },
  taskPanelCollapsedFooter: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 6,
    width: "100%",
    paddingTop: 8,
    borderTop: "1px solid var(--border-dim)",
  },
  taskPanelExpandBtn: {
    position: "relative" as const,
    width: 32,
    height: 32,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-card)",
    color: "var(--text-muted)",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  taskPanelCollapsedNewBtn: taskPanelCollapsedNewBtnBase,
  taskPanelCollapsedNewBtnActive: {
    ...taskPanelCollapsedNewBtnBase,
    color: "var(--control-active-fg)",
  },
  taskPanelCollapsedNewBtnInactive: {
    ...taskPanelCollapsedNewBtnBase,
    color: "var(--text-muted)",
  },
  taskPanelCollapsedSmallBtn: {
    width: 28,
    height: 28,
    border: "none",
    borderRadius: 6,
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  taskPanelAttentionDot: {
    position: "absolute" as const,
    top: 3,
    right: 3,
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "var(--danger)",
    border: "2px solid var(--bg-sidebar)",
    boxSizing: "border-box" as const,
  },
  panelHeader: {
    height: 48,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 10px 0 6px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  backBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 6px",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    color: "var(--text-muted)",
    flexShrink: 0,
  },
  panelCollapseBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    color: "var(--text-hint)",
    flexShrink: 0,
  },
  panelProjectName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  panelSearchWrap: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    margin: "8px 10px 4px",
    padding: "6px 9px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
  },
  panelSearchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
  },
  newTaskRow: newTaskRowBase,
  newTaskRowActive: {
    ...newTaskRowBase,
    background: "var(--control-active-bg)",
    color: "var(--control-active-fg)",
  },
  newTaskRowInactive: {
    ...newTaskRowBase,
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
  },
  newTaskRowLabel: { fontSize: 13, fontWeight: 500 },
  taskActionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "6px 19px 4px",
  },
  taskActionsMeta: { fontSize: 11, color: "var(--text-hint)", letterSpacing: 0.2 },
  taskActionBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 8px",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    background: "var(--bg-card)",
    color: "var(--text-muted)",
    fontSize: 11.5,
    cursor: "pointer",
  },
  taskActionBtnDisabled: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 8px",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    background: "var(--bg-card)",
    color: "var(--text-muted)",
    fontSize: 11.5,
    cursor: "default",
    opacity: 0.45,
  },
  taskDivider: { height: 1, background: "var(--border-dim)", margin: "4px 10px 2px" },
  branchBar: branchBarBase,
  branchBarOpen: { ...branchBarBase, background: "var(--bg-hover)" },
  repoSelectorBar: repoSelectorBarBase,
  repoSelectorBarDisabled: {
    ...repoSelectorBarBase,
    cursor: "not-allowed",
    opacity: 0.68,
  },
  repoSelectorName: {
    flex: 1,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  repoSelectorBadge: {
    fontSize: 10,
    fontWeight: 600,
    color: "var(--text-hint)",
    background: "var(--bg-hover)",
    padding: "0 5px",
    borderRadius: 8,
    flexShrink: 0,
  },
  repoSelectorCheck: { flexShrink: 0, marginLeft: "auto" },
  flexShrinkIcon: { flexShrink: 0 },
  dimChevronIcon: { opacity: 0.58 },
  dimChevronIconStrong: { opacity: 0.7 },
  branchBarName: {
    flex: 1,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  branchDialogBox: {
    width: 360,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 12,
    boxShadow: "var(--shadow-popover)",
    padding: "20px 20px 16px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  branchDialogTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginBottom: 2,
  },
  branchDialogHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  branchDialogHeaderTitle: { display: "flex", alignItems: "center", gap: 8 },
  branchDialogLabel: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 5,
  },
  branchDialogSelectValue: {
    flex: 1,
    textAlign: "left" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  branchDialogActions: { display: "flex", justifyContent: "flex-end", gap: 8 },
  branchPopoverItemDim: { opacity: 0.5 },
  branchPopoverItemNormal: { opacity: 1 },
  branchSwitchIndicator: {
    fontSize: 10,
    color: "var(--text-hint)",
    marginLeft: "auto",
  },
  branchSwitchError: {
    padding: "6px 10px",
    fontSize: 11,
    color: "var(--danger)",
    borderTop: "1px solid var(--border)",
  },
  branchNewItem: { gap: 6 },
  branchNewItemLabel: { fontSize: 12, color: "var(--accent)" },
  branchInput: {
    width: "100%",
    padding: "8px 10px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-ui)",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  branchOptGroup: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    padding: "6px 10px 3px",
    textTransform: "uppercase" as const,
    userSelect: "none" as const,
  },
  branchDialogError: { fontSize: 12, color: "var(--color-error)", padding: "4px 0" },
  taskListScroll: {
    flex: 1,
    overflowY: "auto",
    padding: "2px 0 12px",
    overflowAnchor: "none" as const,
  },
  taskPanelFooter: {
    padding: "10px 10px",
    borderTop: "1px solid var(--border-dim)",
    display: "flex",
    justifyContent: "flex-start",
    background: "var(--bg-sidebar)",
  },
  taskListEmpty: {
    padding: "24px 16px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center",
  },
  groupLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    padding: "10px 14px 3px",
    textTransform: "uppercase" as const,
  },
  taskCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    padding: "7px 12px",
    margin: "1px 6px",
    borderRadius: 6,
    cursor: "pointer",
    transition: "background 0.1s",
  },
  taskCardTitle: {
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  taskCardSub: { fontSize: 11, color: "var(--text-muted)", marginTop: 1 },
  taskDiffStats: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    marginLeft: 8,
    fontSize: 11,
    fontVariantNumeric: "tabular-nums",
  },
  taskDiffAdditions: { color: "var(--diff-add-fg)", fontWeight: 600 },
  taskDiffDeletions: { color: "var(--diff-delete-fg)", fontWeight: 600 },
  agentBadge: {
    flexShrink: 0,
    width: 14,
    height: 14,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  worktreeBadge: {
    position: "absolute" as const,
    right: 36,
    top: 12,
    flexShrink: 0,
    width: 12,
    height: 12,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    pointerEvents: "none" as const,
    transition: "opacity 0.12s ease",
    zIndex: 1,
  },
  taskDeleteBtn: {
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
    transition: "opacity 0.12s ease, background 0.12s ease, color 0.12s ease",
  },
  taskPlayBtn: {
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--accent)",
    cursor: "pointer",
    transition: "opacity 0.12s ease",
  },
  taskStarBtn: {
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    cursor: "pointer",
    transition: "opacity 0.12s ease, color 0.12s ease",
  },
  taskRenameBtn: {
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
    transition: "opacity 0.12s ease, color 0.12s ease",
  },
  taskRenameInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
    background: "var(--bg-input)",
    border: "1px solid var(--control-active-fg)",
    borderRadius: 4,
    padding: "1px 5px",
    outline: "none",
  },
} satisfies Record<string, React.CSSProperties>;
