import type React from "react";

const repoSelectorBarBase = {
  display: "flex",
  alignItems: "center",
  gap: 6,
  width: "calc(100% - 20px)",
  margin: "6px 10px 4px",
  padding: "5px 9px",
  background: "var(--bg-card)",
  border: "1px solid var(--border-dim)",
  borderRadius: 6,
  cursor: "pointer",
  userSelect: "none" as const,
  transition: "background 0.1s, opacity 0.1s",
  textAlign: "left" as const,
} satisfies React.CSSProperties;

const branchBarBase = {
  display: "flex",
  alignItems: "center",
  gap: 6,
  margin: "0 10px 4px",
  padding: "5px 9px",
  background: "var(--bg-card)",
  border: "1px solid var(--border-dim)",
  borderRadius: 6,
  cursor: "pointer",
  userSelect: "none" as const,
  transition: "background 0.1s",
  textAlign: "left" as const,
} satisfies React.CSSProperties;

const taskPanelBase = {
  width: 260,
  flexShrink: 0,
  background: "var(--bg-sidebar)",
  borderRight: "1px solid var(--border-dim)",
  display: "flex",
  flexDirection: "column" as const,
  overflow: "hidden",
} satisfies React.CSSProperties;

const newTaskRowBase = {
  display: "flex",
  alignItems: "center",
  gap: 8,
  width: "calc(100% - 20px)",
  margin: "6px 10px 2px",
  padding: "6px 10px",
  border: "none",
  cursor: "pointer",
  textAlign: "left" as const,
  borderRadius: 6,
  transition: "background 0.1s",
} satisfies React.CSSProperties;

export const task = {
  taskPanel: taskPanelBase,
  panelHeader: {
    /* 36 而非 48：分割线要夹在项目名与搜索框正中，见 project-rail.css 的联立式子。
       22px 头像居中 → 下沿距分割线 7px，等于 panelSearchWrap 的 margin-top。 */
    height: 36,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 10px 0 6px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  panelProjectName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  panelSearchWrap: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    /* 上边距 7 = 分割线到项目名的距离，使分割线居中；搜索框落在 36+7=43px，
       与抽屉那边的 2+32+9 齐平。 */
    margin: "7px 12px 4px",
    padding: "6px 9px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
  },
  panelSearchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
  },
  // 新建任务 = 主操作：用实心主按钮配色（--primary-action-bg，和弹窗里的「保存」同一套），
  // 一眼看出是按钮而不是一行文案；下面的快捷按钮是浅色 chip，层级自然分开。
  newTaskRowPrimary: {
    ...newTaskRowBase,
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    fontWeight: 600,
    transition: "filter 0.1s",
  },
  newTaskRowLabel: { fontSize: 13, fontWeight: 500 },
  // 快捷创建按钮：一排胶囊 chip，末尾的「+」是新增/管理
  presetChipRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 4,
    padding: "0 10px 4px",
  },
  presetChip: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    maxWidth: "100%",
    padding: "4px 9px",
    borderRadius: 999,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
    transition: "background 0.1s, color 0.1s, border-color 0.1s",
  },
  presetChipAdd: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    borderRadius: 999,
    border: "1px dashed var(--border-medium)",
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
    transition: "background 0.1s, color 0.1s",
  },
  presetChipIcon: { width: 11, height: 11, flexShrink: 0 },
  presetChipLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  presetDialogList: { display: "flex", flexDirection: "column" as const, gap: 4, marginBottom: 12 },
  presetDialogRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-card)",
    cursor: "pointer",
  },
  presetDialogRowActive: { borderColor: "var(--control-active-fg)" },
  presetDialogRowText: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" as const, gap: 1 },
  presetDialogRowName: { fontSize: 12.5, fontWeight: 600, color: "var(--text-primary)" },
  presetDialogRowHint: {
    fontSize: 11,
    color: "var(--text-hint)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  presetFieldRow: { display: "flex", flexDirection: "column" as const, gap: 6, marginBottom: 10 },
  presetSwitchRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 },
  taskDivider: { height: 1, background: "var(--border-dim)", margin: "4px 10px 2px" },
  branchBar: branchBarBase,
  branchBarOpen: { ...branchBarBase, background: "var(--bg-hover)" },
  repoSelectorBar: repoSelectorBarBase,
  repoSelectorBarDisabled: {
    ...repoSelectorBarBase,
    cursor: "not-allowed",
    opacity: 0.68,
  },
  repoSelectorName: {
    flex: 1,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  repoSelectorBadge: {
    fontSize: 10,
    fontWeight: 600,
    color: "var(--text-hint)",
    background: "var(--bg-hover)",
    padding: "0 5px",
    borderRadius: 8,
    flexShrink: 0,
  },
  repoSelectorCheck: { flexShrink: 0, marginLeft: "auto" },
  flexShrinkIcon: { flexShrink: 0 },
  dimChevronIconStrong: { opacity: 0.7 },
  branchBarName: {
    flex: 1,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  branchDialogBox: {
    width: 360,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 12,
    boxShadow: "var(--shadow-popover)",
    padding: "20px 20px 16px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  branchDialogTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginBottom: 2,
  },
  branchDialogHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  branchDialogHeaderTitle: { display: "flex", alignItems: "center", gap: 8 },
  branchDialogLabel: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 5,
  },
  branchDialogSelectValue: {
    flex: 1,
    textAlign: "left" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  branchDialogActions: { display: "flex", justifyContent: "flex-end", gap: 8 },
  branchPopoverItemDim: { opacity: 0.5 },
  branchPopoverItemNormal: { opacity: 1 },
  branchSwitchIndicator: {
    fontSize: 10,
    color: "var(--text-hint)",
    marginLeft: "auto",
  },
  branchSwitchError: {
    padding: "6px 10px",
    fontSize: 11,
    color: "var(--danger)",
    borderTop: "1px solid var(--border)",
  },
  branchNewItem: { gap: 6 },
  branchNewItemLabel: { fontSize: 12, color: "var(--accent)" },
  branchInput: {
    width: "100%",
    padding: "8px 10px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-ui)",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  branchDialogError: { fontSize: 12, color: "var(--color-error)", padding: "4px 0" },
  taskListScroll: {
    flex: 1,
    overflowY: "auto",
    padding: "2px 0 12px",
    overflowAnchor: "none" as const,
  },
  taskListEmpty: {
    padding: "24px 16px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center",
  },
  groupLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    padding: "10px 14px 3px",
    textTransform: "uppercase" as const,
  },
  taskCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    padding: "7px 12px",
    margin: "1px 6px",
    borderRadius: 6,
    cursor: "pointer",
    transition: "background 0.1s",
  },
  // 本地 Claude Code 会话详情（非 Nezha 任务）：头部一条元信息 + 复用会话回放
  localSessionView: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
  },
  localSessionHeader: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 16px",
    borderBottom: "1px solid var(--border-dim)",
  },
  localSessionBadge: {
    flexShrink: 0,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-hint)",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 0.4,
  },
  localSessionPreview: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 12.5,
    color: "var(--text-primary)",
  },
  localSessionTime: {
    flexShrink: 0,
    fontSize: 11.5,
    color: "var(--text-hint)",
  },
  taskCardTitle: {
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  taskCardSub: { fontSize: 11, color: "var(--text-muted)", marginTop: 1 },
  taskDiffStats: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    marginLeft: 8,
    fontSize: 11,
    fontVariantNumeric: "tabular-nums",
  },
  taskDiffAdditions: { color: "var(--diff-add-fg)", fontWeight: 600 },
  taskDiffDeletions: { color: "var(--diff-delete-fg)", fontWeight: 600 },
  agentBadge: {
    flexShrink: 0,
    width: 14,
    height: 14,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  worktreeBadge: {
    position: "absolute" as const,
    right: 36,
    top: 12,
    flexShrink: 0,
    width: 12,
    height: 12,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    pointerEvents: "none" as const,
    transition: "opacity 0.12s ease",
    zIndex: 1,
  },
  taskDeleteBtn: {
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
    transition: "opacity 0.12s ease, background 0.12s ease, color 0.12s ease",
  },
  taskStarBtn: {
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    cursor: "pointer",
    transition: "opacity 0.12s ease, color 0.12s ease",
  },
  taskRenameBtn: {
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
    transition: "opacity 0.12s ease, color 0.12s ease",
  },
} satisfies Record<string, React.CSSProperties>;
