import type React from "react";

export const terminal = {
  runHeader: {
    /* 36px 高、内容居中 → 任务名中心落在 18px，与左侧两个面板头部（task.ts 的 panelHeader
       36px、project-rail.css 里「添加项目」按钮中心 18px）连成同一条水平带。 */
    height: 36,
    padding: "0 20px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  runMetricsRow: {
    marginTop: 0,
    display: "flex",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  runMetricPill: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 8px",
    borderRadius: 6,
    background: "var(--bg-input)",
    border: "1px solid var(--border-dim)",
  },
  runMetricPillButton: {
    font: "inherit",
    cursor: "pointer",
  },
  runMetricPillLabel: {
    fontSize: 10,
    color: "var(--text-hint)",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: 0.4,
  },
  runMetricPillValue: {
    fontSize: 11,
    color: "var(--text-primary)",
    fontWeight: 600,
  },
  runSessionFilePillWrap: {
    position: "relative" as const,
    display: "inline-flex",
    alignItems: "center",
  },
  runSessionStatusDot: {
    display: "inline-block",
    position: "static" as const,
    bottom: "auto",
    right: "auto",
    flexShrink: 0,
  },
  runSessionCopyTooltip: {
    position: "absolute" as const,
    left: "50%",
    bottom: "calc(100% + 6px)",
    transform: "translateX(-50%)",
    zIndex: 20,
    padding: "5px 8px",
    borderRadius: 6,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.18)",
    color: "var(--text-secondary)",
    fontSize: 11,
    fontWeight: 600,
    lineHeight: 1.4,
    whiteSpace: "nowrap" as const,
    pointerEvents: "none" as const,
  },
  cancelBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--border-medium)",
    borderRadius: 5,
    fontSize: 12,
    color: "var(--text-muted)",
    cursor: "pointer",
    flexShrink: 0,
  },
  resumeBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--control-active-fg)",
    borderRadius: 5,
    fontSize: 12,
    color: "var(--control-active-fg)",
    cursor: "pointer",
    flexShrink: 0,
  },
  terminalContainer: {
    flex: 1,
    overflow: "hidden" as const,
    padding: "10px 0 10px 10px",
    // 快捷输入按钮浮在会话右下角
    position: "relative" as const,
  },
  quickInputTrigger: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 10px",
    borderRadius: 999,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.16)",
  },
  quickInputMenu: { minWidth: 280, maxWidth: 360 },
  copySessionMenu: { minWidth: 230 },
  handoffContextRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" as const },
  handoffChip: {
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  },
  handoffChipActive: {
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid var(--control-active-fg)",
    background: "var(--control-active-bg)",
    color: "var(--control-active-fg)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  copySessionRecentRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 10px 4px",
  },
  copySessionRecentLabel: { fontSize: 12, color: "var(--text-secondary)", whiteSpace: "nowrap" as const },
  copySessionCountInput: {
    width: 46,
    padding: "3px 6px",
    borderRadius: 5,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 12,
    textAlign: "center" as const,
    outline: "none",
  },
  copySessionCopyBtn: {
    marginLeft: "auto",
    padding: "4px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    fontSize: 12,
    cursor: "pointer",
  },
  // 会话右下角：复制会话 + 快捷输入，并排靠右
  /** 会话记录（SessionView）那一屏：相对定位的容器，好让右下角那排按钮挂上去。 */
  sessionPaneWrap: {
    position: "relative" as const,
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
  },
  sessionCornerActions: {
    position: "absolute" as const,
    right: 14,
    bottom: 14,
    zIndex: 5,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  quickInputEmpty: { padding: "8px 10px", fontSize: 11.5, color: "var(--text-hint)" },
  quickInputRow: { display: "flex", alignItems: "center", gap: 2 },
  quickInputRowMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "flex-start",
    gap: 1,
    padding: "5px 8px",
  },
  quickInputRowLabel: { fontSize: 12, color: "var(--text-primary)" },
  quickInputRowPreview: {
    fontSize: 10.5,
    color: "var(--text-hint)",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  quickInputRowEdit: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 22,
    height: 22,
    marginRight: 4,
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
  },
  quickInputAddRow: { gap: 8, minHeight: 30 },
  quickInputToggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    width: "100%",
    padding: "6px 10px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
  },
  quickInputToggleText: { display: "flex", flexDirection: "column" as const, gap: 1, minWidth: 0 },
  quickInputToggleLabel: { fontSize: 12, color: "var(--text-secondary)" },
  quickInputToggleHint: {
    fontSize: 10.5,
    color: "var(--text-hint)",
    lineHeight: 1.35,
    textAlign: "left" as const,
  },
  interruptedSessionWrap: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    background: "var(--bg-root)",
  },
  interruptedBanner: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: 7,
    minHeight: 38,
    padding: "4px 28px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-root)",
  },
  interruptedBannerIcon: {
    width: 18,
    height: 18,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--warning)",
    flexShrink: 0,
  },
  interruptedBannerBody: {
    minWidth: 0,
    flex: "1 1 180px",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  interruptedBannerTitle: {
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--text-primary)",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerActions: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap" as const,
    gap: 5,
    flexShrink: 0,
  },
  interruptedNoSessionPane: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 32px",
    color: "var(--text-hint)",
    fontSize: 13,
    lineHeight: 1.6,
    textAlign: "center" as const,
  },
  interruptedPrimaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 5,
    border: "1px solid var(--border-dim)",
    color: "var(--text-primary)",
    background: "var(--bg-card)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
